[http]
    client_addr = "0.0.0.0"
    client_port = 8080
    server_addr = "0.0.0.0"
    server_port = 80
    host = "test.loc"
    custom_ids = true
    password = "mysecret"
    [http.tls]
        enabled = false
        cert = ""
        key = ""
[tcp]
    client = ""
    server = ""
    password = "mysecret"
